#!perl -wl
use Mac::Files;
use Mac::Glue ':glue';
use strict;

my $a = new Mac::Glue 'Anarchie';

$a->activate;
$a->settransfermode(enum('tmautomatic'));

my $file = FindFolder(kOnSystemDisk, kDesktopFolderType)
    . ":Mac-Glue-2.html";

my $err = $a->webfetch(
    # putting "$file" instead of "$a->obj(file => $file)"
    # makes Mac::Glue try to resolve it as an alias instead,
    # which is not what we want

    $a->obj(file => $file),
    url => 'http://pudge.net/macperl/Mac-Glue.html'

);
die "Anarchie error: $err" if $err;
