#!perl -wl
use strict;
use Mac::Glue ':glue';

my $g = new Mac::Glue 'Finder';
my $sd = $g->prop('Startup Disk');
my $all = $g->obj(disks => gAll);

print "Startup disk:\n  ", $g->get( $g->prop(name => $sd) );

print "\nAll disks:\n",
    map {"  $_\n"} sort $g->get( $g->prop(name => $all) );

__END__
