#!perl -wl
use Data::Dumper;
use Mac::Glue;
my $finder = new Mac::Glue 'Finder';

$finder->ERRORS( sub { die "We got some error: $_[4]\n" } );

print <<EOT;
We should get two errors here.  If we don't, something went wrong.
Like, you probably have really weird filename or something.
EOT


$finder->open(
	$finder->obj( item => 'kjashdkasdhakjshdasdjkhasd-1' ),
	# override main handler
	ERRORS => \&error_handler
);

# revert back to main handler
$finder->open(
	$finder->obj( item => 'kjashdkasdhakjshdasdjkhasd-2' ),
);

sub error_handler {
	my($glue, $event, $gluename, $eventname,
		$errs, $errn, @args) = @_;
	my $args = join ', ', @args;
	warn "$gluename->$eventname($args) event failed: $errs\n";
}

__END__
