#!perl -wl
# NOTE: position may not be able to be changed under Mac OS 9 Finder
use Mac::Glue;
use strict;

my($vol, $f, $volume, $label, $position, $oldpos);

$f          = new Mac::Glue 'Finder';
$vol        = $f->prop('startup disk');
$position   = $f->prop('position', $vol);
$label      = $f->prop('label_index', $vol);
$oldpos     = $f->get($position);

$f->activate;
$f->set($position, to => [10, 40]);

for (0 .. 2**5) {
    $f->set($label, to => $_);
}

$f->set($position, to => $oldpos);

$f->beep(3);
